config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  root to: 'posts#index'

  resources :users do
    resources :posts
  end

  get '/post_author/:user_id'=> 'posts#posts_by_author', as: :post_author
  get '/viewed_posts' => 'posts#viewed', as: :viewed_posts
  get '/my_posts' => 'posts#my_posts', as: :my_posts
  get '/keyword/:keyword' => 'posts#browse_keyword', as: :browse_keyword

  post '/view/:post_id'    => 'viewings#create', as: :create_view
  post '/users/:user_id/posts/:id/like' => 'posts#like', as: :like_post
  post '/users/:user_id/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/users/:user_id/posts/:id' => 'comments#create', as: :comments

  get '/filter' => 'posts#filter', as: :filter_post
  get '/sort' => 'posts#sort', as: :sort_post

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :post_viewers, :class_name => "Viewing", :foreign_key => "viewed_post_id"
	has_many :keywords, dependent: :destroy
	has_many :comments, dependent: :destroy

	acts_as_votable

	validates :content, presence: true, uniqueness: true, length: {minimum: 20, maximum: 1000}
	validate :detectable_language
	validates :title, presence: true, uniqueness: true, length: {minimum: 3, maximum: 72}

	#Scopes for filtering and sorting
	scope :author, -> (user_id) { where user_id: user_id }
	scope :keyword, -> (keyword) { joins(:keywords).where(keywords: {name: keyword}) }
	scope :already_viewed, -> (user_id) { joins(:post_viewers).where(viewings: {viewer_id: user_id}) }
	scope :not_yet_viewed, -> (user_id) { not_yet_viewed(user_id) }
	scope :most_likes, -> { order(:cached_votes_up => :desc) }
	
	def self.not_yet_viewed(user_id)
		not_mine = where('user_id!=?', user_id)
		already_viewed = joins(:post_viewers).where(viewings: {viewer_id: user_id})
		not_mine - already_viewed
	end


	def detectable_language
		results = AlchemyAPI.search(:language_detection, text: content)
		unless permitted_languages.include?(results["language"])
			errors.add(:content, "content is not in a permitted language.")
		end
	end

	def create_keywords
		response = AlchemyAPI.search(:keyword_extraction, text: self.content)
		#string does not always neccessarily yeild keywords
		if response != nil
			response.each { |item| self.keywords.create(name: item["text"]) }
		end
	end

	private
	def permitted_languages
		["english", "spanish", "french", "german", "italian"]
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include Rewards::Give
	include Rewards::Spend
	before_action :authenticate_user!, :except => [:index, :browse_keyword, :posts_by_author]

	def index
		@posts = Post.all.order(created_at: :desc)
		@viewed_posts = Post.already_viewed(current_user.id) if user_signed_in?
		#@unviewed_posts = @posts - @viewed_posts
	end

	def filter
		@posts = Post.where(nil)
		@viewed_posts = Post.already_viewed(current_user.id) if user_signed_in?
		filtering_params(params).each do |key, value|
		    @posts = @posts.public_send(key, value) if value.present?
		end
		
	end

	def sort
		@posts = Post.where(nil)
		@posts = Post.most_likes
		@viewed_posts = Post.already_viewed(current_user.id) if user_signed_in?
	end

	def show
		@user = current_user
		@post = Post.find(params[:id])
		@comments = @post.comments.order(created_at: :desc)
		@comment = Comment.new
	end

	def viewed
		@user = current_user
		@posts = @user.posts_viewed.order('created_at DESC')
			.map {|post| Post.where('id=?', post.viewed_post_id)}.flatten
	end

	def my_posts
		@user = current_user
		@posts = @user.posts.order('created_at DESC')
	end

	def new
		@user = current_user
		@post = @user.posts.new
	end

	def create
		@post = current_user.posts.new post_params
		if @post.save
			@post.create_keywords
			Rewards::Give.reward_for_publishing_post(current_user, @post)
			redirect_to user_post_path(current_user.id, @post.id)
		else
			render :new
		end
	end

	def like
	  @user = current_user
	  @post = Post.find(params[:id])
	  unless @user.voted_for? @post
	  	@post.liked_by current_user
	  	Rewards::Give.reward_for_receiving_like(current_user, @post)
	  end
	  render 'show'
	end

	def dislike
		@user = current_user
	  	@post = Post.find(params[:id])
	  	@post.disliked_by current_user
	  	render 'show'
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to my_posts_path
	end


	private
	def post_params
		params.require(:post).permit(:title, :content)
	end

	def filtering_params(params)
	  params.slice(:author, :keyword, :already_viewed, :not_yet_viewed)
	end

end


#OLD STUFF FOR REFERENCE
#------------------------
#@posts = Post.author(params[:author]) if params[:author].present?
#@posts = Post.keyword(params[:keyword]) if params[:keyword].present?
#@posts = Post.already_viewed(params[:already_viewed]) if params[:already_viewed].present?
#@posts = Post.not_yet_viewed(params[:not_yet_viewed]) if params[:not_yet_viewed].present?

app/helpers/posts_helper.rb
module PostsHelper
	include Rewards::Spend

	def render_penny_alert(user)
		render ("shared/penny_alert") if user.total_points < VIEWING_POST
	end

	def obscured_post_content_to_html(post)
		content_to_html(post, obscure_non_keywords(post))
	end

	def post_content_to_html(post)
		content_to_html(post, split_keywords_in_content(post))
	end

	def render_post_list_item(post)
		if Post.already_viewed(current_user.id).include? post
			return render("posts/already_viewed", post: post)
		elsif post.user_id == current_user.id
			return render("posts/post_by_user", post: post)
		else
			return render("posts/standard_post", post: post)
		end
	end

	def render_post_status_for(post)
	end

	def render_view_button_for(post)
		if @viewed_posts.include?(post) || current_user.id == post.user_id
			button_to(user_post_path(current_user.id, post.id), method: :get, class: "view-content-btn btn btn-default btn-lg btn-block") do
				"<i class='fa fa-circle'></i>".html_safe
			end
		else
			button_to(create_view_path(post.id), class: "btn btn-primary btn-lg btn-block", disabled: current_user.total_points < VIEWING_POST ? true : false) do
				"<i class='fa fa-circle'></i>".html_safe
			end
		end
	end

	def render_post_tags(post)
		if @viewed_posts.include?(post)
		end
		if post.user_id == current_user.id
		end
	end

	private
	def content_to_html(post, words)
		content = words.inject('') { |a, w| a + keyword_to_html(post, w) }
		"<p>#{content}</p>".html_safe
	end

	def keyword_to_html(post, word)
		if Keyword.recurring_keyword?(word)
			link_to(word, filter_post_path(:keyword => word), style: "font-weight:bold;")
		elsif extract_keywords(post).include?(word)
			"<b>#{word}</b>"
		else
			word
		end
	end

	def extract_keywords(post)
		post.keywords.map { |keyword| keyword.name }
	end

	def obscure_non_keywords(post)
		if post.keywords.any?
			keywords = post.keywords.map { |response_hash| response_hash.name }
	  		#post.content.split(/(#{keywords.join('|')})/).map do |s|
	  		split_keywords_in_content(post).map do |word| 
	  			#keywords.include?(s) ? s : s.gsub(/./) { |c| (c==' ') ? c : "\u25A0".encode('utf-8')}
	  			keywords.include?(word) ? word : substitute_characters(word)
	  		end
	    else
	    	#post.content.gsub(/./) {|a| (a==' ') ? a : "\u25A0".encode('utf-8')}.split(" ")
	    	substitute_characters(post.content).split(" ")
	    end
	end

	def substitute_characters(characters)
		characters.gsub(/./) {|char| (char==' ') ? char : "\u25A0".encode('utf-8')}
	end

	def split_keywords_in_content(post)
	  	post.content.split(/(#{extract_keywords(post).join('|')})/) || []
	end

end

app/views/posts/_already_viewed.html.erb
<h1>already viewed</h1>

app/views/posts/_post_by_user.html.erb
<h1>post by user</h1>

app/views/posts/_posts_list.html.erb
<div class="mansonry-row">
	<% @posts.each do |post| %>

		<div class="col-md-4">
			<div class="post-container">
				<div class="row meta-toolbar">
					<div class="col-md-6">
					<p class="date-published"><%= post.created_at.strftime("%d %b") %>
						<% if user_signed_in? && @viewed_posts.include?(post) %>
								<span class="badge viewed-post-tag" data-toggle="tooltip" data-placement="bottom" title="You already viewed this post. This won't cost you another penny"> Viewed <span class="glyphicon glyphicon-question-sign"></span></span>
						<% end %>
						<% if user_signed_in? && post.user_id == current_user.id %>
								<span class="badge"> My post<span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="bottom" title="This is a post you created."></span></span>
						<% end %>
					</p>
					</div>
					<div class="col-md-6">
						<%= render 'shared/meta_toolbar_counters', post: post %>
					</div>
			    </div>

				<h1>
					<%= post.title %>
					<div class="author-link">
						<%= image_tag User.find(post.user_id).avatar.url(:thumb), class: "avatar" %>
						<%= link_to User.find(post.user_id).name, filter_post_path(:author => post.user_id) %>
					</div>
				</h1>

				<div class="post-content">
					<%= obscured_post_content_to_html(post) %>
				</div>

				<% if user_signed_in? %>
					<%= render_view_button_for post %>
				<% end %>
				
			</div>
		</div>
		
	<% end %>
</div>

app/views/posts/_posts_list_archive.html.erb
<ul class="list-group">
	<% @posts.each do |post| %>
		<li class="list-group-item">
			<div class="row meta-toolbar">
					<div class="col-md-6">
					<p><%= post.created_at.strftime("%d %b") %>
						<% if post.user_id != current_user.id %>
						<span class="date-viewed">(viewed: <%= Viewing.where('viewer_id=? AND viewed_post_id=?', current_user.id, post.id).first.created_at.strftime("%d %b") %>)</span>
						<% end %>
						<% if current_user.voted_up_on? post %>
							<span class="badge"><i class="fa fa-thumbs-up"></i> You liked this post!</span>
						<% elsif current_user.voted_down_on? post %>
							<span class="badge"><i class="fa fa-thumbs-down"></i> You disliked this post!</span>
						<% end %>	


					</p>
					</div>
					<div class="col-md-6">
					<%= render 'shared/meta_toolbar_counters', post: post %>
					</div>
			</div>

			<div class="row">
				<div class="col-md-8">
					<h1>
						<%= post.title %>
						<span class="author-link">
							<%= image_tag User.find(post.user_id).avatar.url(:thumb), class: "avatar" %>
							<%= link_to User.find(post.user_id).name, filter_post_path(:author => post.user_id) %>
						</span>
					</h1>
				</div>
				<div class="col-md-4">
				<div class="right">
					<%= button_to "View Contents", user_post_path(@user.id, post.id), method: :get, class: "btn btn-primary btn-lg"%>
				</div>
				</div>
			</div>
		</li>
	<% end %>
</ul>

app/views/posts/_standard_post.html.erb
<h1>standard</h1>

app/views/posts/_welcome_message.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>
  	A participatory microblogging platform with a twist. When browsing posts, only the title and content
  	keywords are visible. In order access the full contents, you must spend your ‘pennies’.
	You're given a few to spend upon registration, to earn more, publish a post. Likes for your post will also earn you pennies.
  </p>

  <p>
	When browsing, posts you've already spend your pennies on are tagged with 
	<span class="badge viewed-post-tag"> Viewed </span>, posts you created are tagged with
	<span class="badge viewed-post-tag"> My post </span>
  </p>
  <p>
  	<%= link_to new_user_registration_path, method: :get, class: "btn btn-primary btn-lg" do %>
	    <i class="fa fa-pencil"></i> Get Started!
	<% end %>
  </p>
</div>

app/views/posts/filter.html.erb
<div class="page-header">
  <% if params[:author] %>
		<h3>Posts By Author: <%= image_tag User.find(params[:author]).avatar.url(:small) %> 
			<%= User.find(params[:author]).name %></h3>
	<% elsif params[:keyword] %>
		<h3>Posts By Keyword: '<%= params[:keyword] %>'</h3>
	<% elsif params[:already_viewed] %>
		<h3>Posts Already Viewed</h3>
	<% elsif params[:not_yet_viewed] %>
		<h3>Posts Not Yet Viewed</h3>
	<% else %>
		<h3>Filtered Posts</h3>
	<% end %>
</div>

<%= render_penny_alert current_user %>
<%= render 'posts_list' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	<div class="page-header">
	  <h3>All Posts</h3>
	</div>
	<%= render_penny_alert current_user %>
<% else %>
	<%= render 'posts/welcome_message' %>
<% end %>

<%= render 'posts/posts_list' %>

app/views/posts/my_posts.html.erb
<div class="page-header">
  <h3>My Posts (<%= @posts.count %>)</h3>
</div>

<%= render 'posts_list_archive' %>

app/views/posts/new.html.erb
		<div class="page-header">
		  <h3>Create New Post</h3>
		</div>

<div class="row">
	<div class="col-md-6">
		<% if @post.errors.any? %>
			<ul>
				<% @post.errors.full_messages.each do |error_msg| %>
					<li><%= error_msg %></li>
				<% end %>	
			</ul>
		<% end %>

		<%= form_for [current_user, @post], html: { method: :post } do |f| %>
			<%= f.text_field :title, placeholder: 'Post Title' %>
			<%= f.text_area :content, placeholder: 'Post content', rows: 5 %>
			<%= f.submit('Publish', class: "btn btn-primary btn-lg btn-block") %><br />	
		<% end %>
		<%= button_to 'Cancel', :back, method: :get, class: "btn btn-default btn-lg btn-block" %>

	</div>
</div>

app/views/posts/show.html.erb
<div class="single-post-container">
    <div class="row">
        <div class="col-md-8">
          <h1>
            <%= @post.title %>
            <span class="author-link">
                <%= image_tag User.find(@post.user_id).avatar.url(:thumb), class: "avatar" %>
                <%= link_to User.find(@post.user_id).name, filter_post_path(:author => @post.user_id) %>
            </span>
          </h1>
        </div>
        <div class="col-md-4">
          <div class="button-group right">
              <% if @post.user_id == current_user.id %>
                        <%= button_to [current_user, @post], method: :delete, class: "btn btn-default btn-sm" do %>
                        <span class="glyphicon glyphicon-trash white"></span>Delete this post
                        <% end %>
              <% else %>
                
                <% if current_user.voted_as_when_voted_for @post %>
                    <span class="badge"><i class="fa fa-thumbs-up"></i> You liked this post!</span>
                <% elsif current_user.voted_as_when_voted_for(@post).nil? %>
                    <%= button_to like_post_path(current_user, @post), :remote => true, method: :post, class: "btn btn-primary btn-sm like-button" do %>
                    <span class="glyphicon glyphicon-thumbs-up white"></span>Like
                    <% end %>
                    <%= button_to dislike_post_path(current_user, @post), :remote => true, method: :post, class: "btn btn-primary btn-sm dislike-button" do %>
                        <span class="glyphicon glyphicon-thumbs-down white"></span>Dislike
                    <% end %>
                <% else %>
                    <span class="badge"><i class="fa fa-thumbs-down"></i> You disliked this post!</span>
                <% end %>

              <% end %>
          </div>
        </div>
    </div>
    <div class="row meta-toolbar">
        <div class="col-md-6">
            <p><%= @post.created_at.strftime("%d %b") %></p>
        </div>
        <div class="col-md-6">
            <%= render 'shared/meta_toolbar_counters', post: @post %>
        </div>
    </div>
    <div class="post-content">
        <%= post_content_to_html(@post) %>
    </div>
    <div class="row">
        <div class="col-md-3 right">
            <%= button_to :back, method: :get, class: 'btn btn-default btn-md right' do %>
                <i class="fa fa-step-backward"></i> Back
            <% end %>
            
        </div>
    </div>
</div>


<div class="comments-section">
        <div class="row">
            <div class="col-md-12">
                <h3>Comments <small>(<%= @comments.count %>)</small></h3>
            </div>
        </div>
        <div class="row">

            <% if @comment.errors.any? %>
                <ul>
                    <% @comment.errors.full_messages.each do |error_msg| %>
                        <li><%= error_msg %></li>
                    <% end %>   
                </ul>
            <% end %>


            <div class="col-md-12 comment-form">
                <div class="row">
                    <%= form_for @comment, html: { method: :post } do |f| %>
                    <div class="col-md-9">
                        <%= f.text_field :body, placeholder: 'Comment...' %>
                    </div>
                    <div class="col-md-3">
                        <%= f.submit 'Add', :class => 'btn btn-primary btn-md' %>
                    </div>
                    <% end %>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12 comment-list">
                <ul class="media-list">
                    <% if @post.comments.count > 0 %>
                        <% @comments.each do |comment| %>
                            <li class="media">
                                <div class="media-body">
                                <h4 class="media-heading">
                                    <%= image_tag User.find(comment.user_id).avatar.url(:thumb), class: "avatar" %>
                                    <%= link_to User.find(comment.user_id).name, filter_post_path(:author => comment.user_id) %>
                                </h4>
                                <%= comment.body %>
                                </div>
                            </li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>

</div>

app/views/posts/sort.html.erb
<div class="page-header">
	<% if params[:format] === 'most_likes' %>
		<h3>Sort By Likes</h3>
	<% else %>
		<h3>Sort Search</h3>
	<% end %>
</div>

<%= render_penny_alert current_user %>
<%= render 'posts_list' %>

app/views/posts/viewed.html.erb
<div class="page-header">
  <h3>Viewed Posts (<%= @posts.count %>)</h3>
</div>



<%= render 'posts_list_archive' %>