config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  root to: 'posts#index'

  resources :users do
    resources :posts
  end

  get '/post_author/:user_id'=> 'posts#posts_by_author', as: :post_author
  get '/viewed_posts' => 'posts#viewed', as: :viewed_posts
  get '/my_posts' => 'posts#my_posts', as: :my_posts
  get '/keyword/:keyword' => 'posts#browse_keyword', as: :browse_keyword

  post '/view/:post_id'    => 'viewings#create', as: :create_view
  post '/users/:user_id/posts/:id/like' => 'posts#like', as: :like_post
  post '/users/:user_id/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/users/:user_id/posts/:id' => 'comments#create', as: :comments

  get '/filter' => 'posts#filter', as: :filter_post
  get '/sort' => 'posts#sort', as: :sort_post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myproject</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Penny For Your Posts", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Posts", root_path %></li>
		
		<% if user_signed_in? %>
	        <li class="dropdown">
		      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
		          Browse by <span class="caret"></span></a>
		      <ul class="dropdown-menu" role="menu">
		          <li><%= link_to "Posts by me", filter_post_path(:author => current_user.id) %></li>
		          <li><%= link_to "Already viewed", filter_post_path(:already_viewed => current_user.id) %></li>
		   		  <li><%= link_to "Not yet viewed", filter_post_path(:not_yet_viewed => current_user.id) %></li>
		   		  <li><%= link_to "Likes", sort_post_path(:most_likes) %></li>
	          </ul>
	        </li>
        <% end %>
        

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
	      	<li>
				<%= button_to user_path(current_user.id), method: :get, class: "btn btn-primary navbar-btn" do %>
					<span class="glyphicon glyphicon-record" ></span> <%= current_user.total_points %>
				<% end %>
	        </li>
	      	<li>
	        	<%= button_to new_user_post_path(current_user.id), method: :get, class: "btn btn-default navbar-btn" do %>
	                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>New Post
	            <% end %>
	        </li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
			  <%= image_tag current_user.avatar.url(:small), class: "avatar" %>
	          <%= current_user.name %> <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><%= link_to "Viewed Posts Archive", viewed_posts_path %></li>
	            <li><%= link_to "My Posts Archive", my_posts_path %></li>
	            <li><%= link_to "Event Log", user_path(current_user) %></li>
	            <li class="divider"></li>
	            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
	            <li><%= link_to "Log out", destroy_user_session_path, method: 'DELETE' %></li>
	          </ul>
	    <% else %>
	        <li><%= button_to new_user_session_path, method: :get, class: "btn btn-primary navbar-btn" do %>
	        		<i class="fa fa-sign-in"></i> Sign in
	        	<% end %>
	        </li>
	        <li><%= button_to new_user_registration_path, method: :get, class: "btn btn-primary navbar-btn" do %>
	        		<i class="fa fa-pencil"></i> Sign up
	        	<% end %>
	        </li>
          <% end %>
          
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</div>

	<footer>
		<div class="container">
	        <p>A project by <a href="http://www.kimwienands.com">Kim Wienands</a>
	        for <a href="http://www.ironhack.com">Ironhack</a> Web Development Bootcamp 2015</p>
	    </div>
	</footer>
</body>
</html>